Added all the source files.
GDGVIT/ConanGUI pull request #3
Opened 2020-02-23 13:17 UTC by Roidujeu

2020-02-24 13:52 UTC, supercmmetry commented on barbarian.cpp
> +    char combined_Buffer[100];
Possibility of segmentation fault.

2020-02-24 14:05 UTC, supercmmetry requested changes
- Check whether Conan is installed on target machine.
 - Resolve potential segmentation faults.
 - Tidy CmakeList

2020-02-24 14:05 UTC, supercmmetry commented on barbarian.cpp
> +    char combined_Buffer[100];
Possibility of segmentation fault. Instead use std::string

2020-02-24 14:05 UTC, supercmmetry commented on CMakeLists.txt
> +if(ANDROID)
Remove build process for platforms non-specific for the project.

2020-02-24 14:05 UTC, supercmmetry commented on main.cpp
> +int main(int argc, char *argv[])
Check whether conan is installed in target machine.

2020-02-24 14:05 UTC, supercmmetry commented on barbarian.cpp
> +    char Full_Path_Rem[100];
Possible segmentation fault. Use std::string instead.

2020-02-24 14:05 UTC, supercmmetry commented on barbarian.cpp
> +        char Conan_Install_Command[100];
Possible segmentation fault. Use std::string instead.

2020-03-23 12:56 UTC, Geek-ubaid commented
@Roidujeu  do the suuggested changes and push a latest commit

2020-03-25 15:44 UTC, merged